name: M3U Update
on:
  push:
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Download IPV4 MU3 File
      run: |
        wget https://live.fanmingming.com/tv/m3u/index.m3u -O public/ipv4.m3u
    - name: Calculate Hash of Downloaded IPV4 MU3 File
      run: |
        IPV4_SHA256=$(sha256sum ipv4.m3u | awk '{print $1}')
        echo "Downloaded file SHA256: $IPV4_SHA256"
    - name: Calculate Hash of Repository File
      run: |
        IPV4_REPO_SHA256=$(sha256sum $(pwd)/public/ipv4.m3u | awk '{print $1}')
        echo "Repository file SHA256: $IPV4_REPO_SHA256"
    - name: Compare Hashes
      id: compare_hashes
      run: |
        if [ "$IPV4_SHA256" == "$IPV4_REPO_SHA256" ]; then
          echo "File consistency"
        else
          echo "Inconsistent files"
        fi
    - name: Update IPV4_M3U Files
      run: |
        if [ "$IPV4_SHA256" != "$IPV4_REPO_SHA256" ]; then
          rm -f public/ipv4.m3u && wget https://live.fanmingming.com/tv/m3u/index.m3u -O public/ipv4.m3u
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add public/ipv4.m3u
          git commit -m "m3u Automatic Update."
          echo "The file has been successfully updated"
        else
          echo "File not updated, no need to replace"
        fi
    #- name: Update IPV6_M3U Files
    #  run: |
    #    rm -f public/ipv6.m3u && wget https://live.fanmingming.com/tv/m3u/ipv6.m3u -O public/ipv6.m3u
    #    git config --local user.name "github-actions[bot]"
    #    git config --local user.email "github-actions[bot]@users.noreply.github.com"
    #    git add public/ipv6.m3u
    #    git commit -m "m3u Automatic Update."

    #- name: Push Changes
    #  run: git push -f origin main || echo "No changes to commit"
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}