name: M3U Update
on:
  push:
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'

permissions:
  pages: write
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update IPV4_M3U Files
      run: |
        rm -f public/ipv4.m3u
        git clone --quiet https://github.com/fanmingming/live.git --depth 1 --branch main fanmingming
        cp -r fanmingming/tv/m3u/index.m3u public/ipv4.m3u
        rm -rf fanmingming
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add public/ipv4.m3u
        git commit -m "ipv4.m3u Automatic Update." || echo "No changes to ipv4 commit"
    - name: Update IPV6_M3U Files
      run: |
        rm -f public/ipv4.m3u
        git clone --quiet https://github.com/fanmingming/live.git --depth 1 --branch main fanmingming
        cp -r fanmingming/tv/m3u/ipv6.m3u public/ipv6.m3u
        rm -rf fanmingming
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add public/ipv6.m3u
        git commit -m "ipv6.m3u Automatic Update." || echo "No changes to ipv6 commit"

    - name: Push changes
      run: git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}